---
# ====== Application: Hospital Management System =============
identification: 
  name: Hospital Management System
  alias: HOSPITAL-MANAGEMENT-SYSTEM
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Native Printing

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: false
  compatibility-mode: 24.2
  accessible-read-only-items: true
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEX Accounts # 8093400940603985

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended

database-session: 
  parsing-schema: TEST

globalization: 
  primary-language: English (en)
  document-direction: Language Default
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: Hospital Management System

progressive-web-app: 
  enable: true
  installable: false
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Home

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - t-TreeNav--styleA
  - js-navCollapsed--hidden
  list-position: Side
  list: Navigation Menu # 8094271037603993

navigation-bar: 
  implementation: List
  list: Navigation Bar # 8095436745604060
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: false

subscription: 
  version-number: 28962828

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: Hospital Management System

component-settings: 
- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 8089003874603971
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 26721861

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 8089211799603975
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 26721862

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 8089506863603975
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  subscription: 
    version-number: 26721862

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 8089850009603975
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  subscription: 
    version-number: 26721862

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 8090190683603976
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 26721862

- # ====== Component Setting: NATIVE_BOSS ======================
  id: 8090488669603976
  identification: 
    name: NATIVE_BOSS
    type: REST Data Source

  subscription: 
    version-number: 26721862

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 8090763737603976
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 26721862

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 8091077354603978
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 26721862

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 8091370966603978
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  subscription: 
    version-number: 26721862

- # ====== Component Setting: NATIVE_IR ========================
  id: 8091672192603978
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 26721862

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 8091968076603979
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  subscription: 
    version-number: 26721862

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 8092278860603979
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  subscription: 
    version-number: 26721862

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 8092514333603979
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  subscription: 
    version-number: 26721862

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 8092822250603981
  identification: 
    name: NATIVE_YES_NO
    type: Item

  subscription: 
    version-number: 26721862

